//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLang.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLang.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Clicked {0} time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_ButtonFace_1st_Clicked {
            get {
                return ResourceManager.GetString("MainPage_ButtonFace_1st_Clicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clicked {0} times に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_ButtonFace_2nd_Clicked {
            get {
                return ResourceManager.GetString("MainPage_ButtonFace_2nd_Clicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click me に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_ButtonFace_Default {
            get {
                return ResourceManager.GetString("MainPage_ButtonFace_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change ColorMode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_ButtonFace_ExchgResource {
            get {
                return ResourceManager.GetString("MainPage_ButtonFace_ExchgResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to
        ///.NET Multi-platform App UI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_Description {
            get {
                return ResourceManager.GetString("MainPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hello, World! - MultiLang.Resources に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_Subject {
            get {
                return ResourceManager.GetString("MainPage_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home(en) - MultiLang.Resources に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
    }
}
